[2022-09-09T19:05:24.483+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: spark_pedidos_silver.pedidos-silver scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-09-09T19:05:24.492+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: spark_pedidos_silver.pedidos-silver scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-09-09T19:05:24.492+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-09T19:05:24.492+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-09T19:05:24.492+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-09T19:05:25.009+0000] {taskinstance.py:1389} INFO - Executing <Task(SparkSubmitOperator): pedidos-silver> on 2022-01-01 00:00:00+00:00
[2022-09-09T19:05:25.014+0000] {standard_task_runner.py:52} INFO - Started process 717 to run task
[2022-09-09T19:05:25.018+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'spark_pedidos_silver', 'pedidos-silver', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_pedidos.py', '--cfg-path', '/tmp/tmpl8ppiykc', '--error-file', '/tmp/tmpmbg0dm7q']
[2022-09-09T19:05:25.018+0000] {standard_task_runner.py:80} INFO - Job 36: Subtask pedidos-silver
[2022-09-09T19:05:25.599+0000] {task_command.py:371} INFO - Running <TaskInstance: spark_pedidos_silver.pedidos-silver scheduled__2022-01-01T00:00:00+00:00 [running]> on host cea5bc5c0a31
[2022-09-09T19:05:26.297+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=juacy
AIRFLOW_CTX_DAG_ID=spark_pedidos_silver
AIRFLOW_CTX_TASK_ID=pedidos-silver
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:00:00+00:00
[2022-09-09T19:05:26.306+0000] {base.py:68} INFO - Using connection ID 'conexao_spark' for task execution.
[2022-09-09T19:05:26.307+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://fe77514119f4:7077 --name arrow-spark ./dags/atividade_1.py
[2022-09-09T19:05:55.127+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO SparkContext: Running Spark version 3.3.0
[2022-09-09T19:05:55.201+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-09-09T19:05:55.338+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO ResourceUtils: ==============================================================
[2022-09-09T19:05:55.340+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO ResourceUtils: No custom resources configured for spark.driver.
[2022-09-09T19:05:55.341+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO ResourceUtils: ==============================================================
[2022-09-09T19:05:55.341+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO SparkContext: Submitted application: arrow-spark
[2022-09-09T19:05:55.369+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2022-09-09T19:05:55.387+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO ResourceProfile: Limiting resource is cpu
[2022-09-09T19:05:55.388+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2022-09-09T19:05:55.460+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO SecurityManager: Changing view acls to: default
[2022-09-09T19:05:55.460+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO SecurityManager: Changing modify acls to: default
[2022-09-09T19:05:55.462+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO SecurityManager: Changing view acls groups to:
[2022-09-09T19:05:55.464+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO SecurityManager: Changing modify acls groups to:
[2022-09-09T19:05:55.467+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(default); groups with view permissions: Set(); users  with modify permissions: Set(default); groups with modify permissions: Set()
[2022-09-09T19:05:55.978+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:55 INFO Utils: Successfully started service 'sparkDriver' on port 39843.
[2022-09-09T19:05:56.146+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO SparkEnv: Registering MapOutputTracker
[2022-09-09T19:05:56.229+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO SparkEnv: Registering BlockManagerMaster
[2022-09-09T19:05:56.277+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2022-09-09T19:05:56.279+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2022-09-09T19:05:56.288+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2022-09-09T19:05:56.329+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-04d27f26-9aee-4803-9227-4c96790baeaf
[2022-09-09T19:05:56.355+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2022-09-09T19:05:56.404+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO SparkEnv: Registering OutputCommitCoordinator
[2022-09-09T19:05:56.817+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2022-09-09T19:05:56.830+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2022-09-09T19:05:56.958+0000] {spark_submit.py:488} INFO - 22/09/09 19:05:56 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://fe77514119f4:7077...
[2022-09-09T19:06:16.959+0000] {spark_submit.py:488} INFO - 22/09/09 19:06:16 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://fe77514119f4:7077...
[2022-09-09T19:06:46.852+0000] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 225, in heartbeat
    self.heartbeat_callback(session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 186, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 885, in refresh_from_db
    ti = qry.first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-09-09T19:06:49.494+0000] {spark_submit.py:488} INFO - 22/09/09 19:06:49 WARN TransportClientFactory: DNS resolution failed for fe77514119f4:7077 took 52524 ms
[2022-09-09T19:06:49.502+0000] {spark_submit.py:488} INFO - 22/09/09 19:06:49 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://fe77514119f4:7077...
[2022-09-09T19:06:49.706+0000] {spark_submit.py:488} INFO - 22/09/09 19:06:49 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master fe77514119f4:7077
[2022-09-09T19:06:49.706+0000] {spark_submit.py:488} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2022-09-09T19:06:49.706+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2022-09-09T19:06:49.706+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2022-09-09T19:06:49.706+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2022-09-09T19:06:49.706+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2022-09-09T19:06:49.706+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - Caused by: java.io.IOException: Failed to connect to fe77514119f4:7077
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2022-09-09T19:06:49.707+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - ... 4 more
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - Caused by: java.net.UnknownHostException: fe77514119f4
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
[2022-09-09T19:06:49.708+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2022-09-09T19:06:49.709+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2022-09-09T19:06:49.710+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2022-09-09T19:06:49.711+0000] {spark_submit.py:488} INFO - ... 1 more
[2022-09-09T19:07:09.757+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2022-09-09T19:07:09.758+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2022-09-09T19:07:09.766+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36103.
[2022-09-09T19:07:09.766+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO NettyBlockTransferService: Server created on cea5bc5c0a31:36103
[2022-09-09T19:07:09.768+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2022-09-09T19:07:09.775+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO SparkUI: Stopped Spark web UI at http://cea5bc5c0a31:4041
[2022-09-09T19:07:09.777+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, cea5bc5c0a31, 36103, None)
[2022-09-09T19:07:09.781+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO StandaloneSchedulerBackend: Shutting down all executors
[2022-09-09T19:07:09.782+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO BlockManagerMasterEndpoint: Registering block manager cea5bc5c0a31:36103 with 434.4 MiB RAM, BlockManagerId(driver, cea5bc5c0a31, 36103, None)
[2022-09-09T19:07:09.784+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, cea5bc5c0a31, 36103, None)
[2022-09-09T19:07:09.784+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2022-09-09T19:07:09.785+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, cea5bc5c0a31, 36103, None)
[2022-09-09T19:07:09.789+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2022-09-09T19:07:09.802+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2022-09-09T19:07:09.950+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO MemoryStore: MemoryStore cleared
[2022-09-09T19:07:09.950+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO BlockManager: BlockManager stopped
[2022-09-09T19:07:09.965+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO BlockManagerMaster: BlockManagerMaster stopped
[2022-09-09T19:07:09.986+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2022-09-09T19:07:10.004+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:09 ERROR AsyncEventQueue: Listener AppStatusListener threw an exception
[2022-09-09T19:07:10.004+0000] {spark_submit.py:488} INFO - java.lang.NullPointerException
[2022-09-09T19:07:10.005+0000] {spark_submit.py:488} INFO - at org.apache.spark.status.AppStatusListener.onApplicationEnd(AppStatusListener.scala:192)
[2022-09-09T19:07:10.005+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:57)
[2022-09-09T19:07:10.006+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
[2022-09-09T19:07:10.006+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
[2022-09-09T19:07:10.007+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
[2022-09-09T19:07:10.007+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
[2022-09-09T19:07:10.007+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
[2022-09-09T19:07:10.007+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
[2022-09-09T19:07:10.008+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
[2022-09-09T19:07:10.008+0000] {spark_submit.py:488} INFO - at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[2022-09-09T19:07:10.008+0000] {spark_submit.py:488} INFO - at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[2022-09-09T19:07:10.008+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
[2022-09-09T19:07:10.008+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
[2022-09-09T19:07:10.008+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
[2022-09-09T19:07:10.008+0000] {spark_submit.py:488} INFO - at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
[2022-09-09T19:07:10.021+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:10 ERROR SparkContext: Error initializing SparkContext.
[2022-09-09T19:07:10.022+0000] {spark_submit.py:488} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2022-09-09T19:07:10.022+0000] {spark_submit.py:488} INFO - at scala.Predef$.require(Predef.scala:281)
[2022-09-09T19:07:10.022+0000] {spark_submit.py:488} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2022-09-09T19:07:10.022+0000] {spark_submit.py:488} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:650)
[2022-09-09T19:07:10.022+0000] {spark_submit.py:488} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2022-09-09T19:07:10.022+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2022-09-09T19:07:10.022+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2022-09-09T19:07:10.022+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-09-09T19:07:10.023+0000] {spark_submit.py:488} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2022-09-09T19:07:10.023+0000] {spark_submit.py:488} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2022-09-09T19:07:10.023+0000] {spark_submit.py:488} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2022-09-09T19:07:10.023+0000] {spark_submit.py:488} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2022-09-09T19:07:10.023+0000] {spark_submit.py:488} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2022-09-09T19:07:10.023+0000] {spark_submit.py:488} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2022-09-09T19:07:10.023+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2022-09-09T19:07:10.024+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2022-09-09T19:07:10.024+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2022-09-09T19:07:10.024+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:10 INFO SparkContext: SparkContext already stopped.
[2022-09-09T19:07:10.024+0000] {spark_submit.py:488} INFO - Traceback (most recent call last):
[2022-09-09T19:07:10.024+0000] {spark_submit.py:488} INFO - File "/opt/***/dags/atividade_1.py", line 6, in <module>
[2022-09-09T19:07:10.024+0000] {spark_submit.py:488} INFO - spark = SparkSession.builder.getOrCreate()
[2022-09-09T19:07:10.024+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 269, in getOrCreate
[2022-09-09T19:07:10.024+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 483, in getOrCreate
[2022-09-09T19:07:10.025+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 208, in __init__
[2022-09-09T19:07:10.025+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 282, in _do_init
[2022-09-09T19:07:10.025+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 402, in _initialize_context
[2022-09-09T19:07:10.026+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1586, in __call__
[2022-09-09T19:07:10.026+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 328, in get_return_value
[2022-09-09T19:07:10.027+0000] {spark_submit.py:488} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2022-09-09T19:07:10.027+0000] {spark_submit.py:488} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2022-09-09T19:07:10.027+0000] {spark_submit.py:488} INFO - at scala.Predef$.require(Predef.scala:281)
[2022-09-09T19:07:10.027+0000] {spark_submit.py:488} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2022-09-09T19:07:10.027+0000] {spark_submit.py:488} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:650)
[2022-09-09T19:07:10.028+0000] {spark_submit.py:488} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2022-09-09T19:07:10.028+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2022-09-09T19:07:10.028+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2022-09-09T19:07:10.028+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-09-09T19:07:10.028+0000] {spark_submit.py:488} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2022-09-09T19:07:10.028+0000] {spark_submit.py:488} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2022-09-09T19:07:10.028+0000] {spark_submit.py:488} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2022-09-09T19:07:10.028+0000] {spark_submit.py:488} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2022-09-09T19:07:10.029+0000] {spark_submit.py:488} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2022-09-09T19:07:10.029+0000] {spark_submit.py:488} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2022-09-09T19:07:10.029+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2022-09-09T19:07:10.030+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2022-09-09T19:07:10.030+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2022-09-09T19:07:10.030+0000] {spark_submit.py:488} INFO - 
[2022-09-09T19:07:10.073+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:10 INFO SparkContext: Successfully stopped SparkContext
[2022-09-09T19:07:10.085+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:10 INFO ShutdownHookManager: Shutdown hook called
[2022-09-09T19:07:10.085+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:10 INFO ShutdownHookManager: Deleting directory /tmp/spark-cc38b7ac-fc1b-4298-917c-6a24929dc305
[2022-09-09T19:07:10.088+0000] {spark_submit.py:488} INFO - 22/09/09 19:07:10 INFO ShutdownHookManager: Deleting directory /tmp/spark-99f5c4f5-2144-4196-8e69-cfd289837f39
[2022-09-09T19:07:10.324+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 420, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://fe77514119f4:7077 --name arrow-spark ./dags/atividade_1.py. Error code is: 1.
[2022-09-09T19:07:10.329+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_pedidos_silver, task_id=pedidos-silver, execution_date=20220101T000000, start_date=20220909T190524, end_date=20220909T190710
[2022-09-09T19:07:10.898+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 36 for task pedidos-silver (Cannot execute: spark-submit --master spark://fe77514119f4:7077 --name arrow-spark ./dags/atividade_1.py. Error code is: 1.; 717)
[2022-09-09T19:07:10.911+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-09T19:07:11.457+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
